import type { QuizQuestion } from "./types";

export const differentialQuestions: QuizQuestion[] = [
  {
    id: "diff-001",
    topic: "differential",
    prompt: "Solve: dy/dx = 2x, with y(0) = 1.",
    promptLatex: "\\frac{dy}{dx} = 2x, \\quad y(0) = 1",
    options: ["y = x²", "y = x² + 1", "y = 2x + 1", "y = x² - 1"],
    optionsLatex: [
      "y = x^2",
      "y = x^2 + 1",
      "y = 2x + 1",
      "y = x^2 - 1",
    ],
    answerIndex: 1,
    explanation: "Integrate: y = ∫2x dx = x² + C. Using y(0)=1 gives C=1, so y = x² + 1",
    explanationLatex: "y = \\int 2x \\, dx = x^2 + C \\implies y(0) = 1 \\therefore C = 1",
    references: [{ label: "Differential Equations", url: "https://en.wikipedia.org/wiki/Differential_equation" }],
  },
  {
    id: "diff-002",
    topic: "differential",
    prompt: "What is the order of differential equation: y''' + 3y'' - 2y' + y = 0?",
    promptLatex: "y''' + 3y'' - 2y' + y = 0",
    options: ["1", "2", "3", "4"],
    answerIndex: 2,
    explanation: "The highest derivative is y''' (third derivative), so order = 3.",
    references: [{ label: "Order of DE", url: "https://en.wikipedia.org/wiki/Differential_equation" }],
  },
  {
    id: "diff-003",
    topic: "differential",
    prompt: "Solve: dy/dx + y = 0.",
    promptLatex: "\\frac{dy}{dx} + y = 0",
    options: ["y = Ceˣ", "y = Ce⁻ˣ", "y = Ceˣ + 1", "y = sin(x) + C"],
    optionsLatex: [
      "y = Ce^x",
      "y = Ce^{-x}",
      "y = Ce^x + 1",
      "y = \\sin x + C",
    ],
    answerIndex: 1,
    explanation: "This is a first-order linear ODE. Solution: y = Ce⁻ˣ",
    explanationLatex: "\\frac{dy}{dx} = -y \\implies y = Ce^{-x}",
    references: [{ label: "First Order DE", url: "https://en.wikipedia.org/wiki/Linear_differential_equation" }],
  },
  {
    id: "diff-004",
    topic: "differential",
    prompt: "What is the auxiliary equation for: y'' - 3y' + 2y = 0?",
    promptLatex: "y'' - 3y' + 2y = 0",
    options: ["r² - 3r + 2 = 0", "r² + 3r + 2 = 0", "r² - 3r - 2 = 0", "r² + 3r - 2 = 0"],
    answerIndex: 0,
    explanation: "Substitute y = eʳˣ to get r² - 3r + 2 = 0.",
    explanationLatex: "y = e^{rx} \\implies r^2 - 3r + 2 = 0",
    references: [{ label: "Characteristic Equation", url: "https://en.wikipedia.org/wiki/Characteristic_equation_(calculus)" }],
  },
  {
    id: "diff-005",
    topic: "differential",
    prompt: "Find the particular solution of y'' + y = 0 with y(0)=1, y'(0)=0.",
    promptLatex: "y'' + y = 0, \\quad y(0)=1, \\; y'(0)=0",
    options: ["y = sin(x)", "y = cos(x)", "y = eˣ", "y = e⁻ˣ"],
    optionsLatex: [
      "y = \\sin x",
      "y = \\cos x",
      "y = e^x",
      "y = e^{-x}",
    ],
    answerIndex: 1,
    explanation: "General solution: y = A cos(x) + B sin(x). y(0)=1 gives A=1. y'(0)=0 gives B=0. So y = cos(x).",
    explanationLatex: "y = A\\cos x + B\\sin x \\implies A=1, B=0 \\therefore y = \\cos x",
    references: [{ label: "Second Order DE", url: "https://en.wikipedia.org/wiki/Ordinary_differential_equation" }],
  },
  {
    id: "diff-006",
    topic: "differential",
    prompt: "Is the DE (y')² + y = 0 linear or nonlinear?",
    promptLatex: "(y')^2 + y = 0",
    options: ["Linear", "Nonlinear"],
    answerIndex: 1,
    explanation: "The term (y')² makes it nonlinear because the derivative appears squared.",
    references: [{ label: "Nonlinear DE", url: "https://en.wikipedia.org/wiki/Nonlinear_differential_equation" }],
  },
  {
    id: "diff-007",
    topic: "differential",
    prompt: "Solve the exact DE: (2xy)dx + (x² + 1)dy = 0.",
    promptLatex: "(2xy)\\,dx + (x^2 + 1)\\,dy = 0",
    options: ["x²y + y = C", "xy² + x = C", "x² + y² = C", "x²y² = C"],
    optionsLatex: [
      "x^2 y + y = C",
      "xy^2 + x = C",
      "x^2 + y^2 = C",
      "x^2 y^2 = C",
    ],
    answerIndex: 0,
    explanation: "∂M/∂y = 2x = ∂N/∂x, so exact. F = ∫M dx = x²y + g(y). Then ∂F/∂y = x² + g'(y) = x² + 1 ⇒ g'(y)=1 ⇒ g(y)=y. Solution: x²y + y = C.",
    explanationLatex: "F = x^2 y + y = C",
    references: [{ label: "Exact DE", url: "https://en.wikipedia.org/wiki/Exact_differential_equation" }],
  },
  {
    id: "diff-008",
    topic: "differential",
    prompt: "What is the integrating factor for dy/dx + (1/x)y = x?",
    promptLatex: "\\frac{dy}{dx} + \\frac{1}{x}y = x",
    options: ["x", "1/x", "eˣ", "ln(x)"],
    optionsLatex: ["x", "\\frac{1}{x}", "e^x", "\\ln x"],
    answerIndex: 0,
    explanation: "IF = exp(∫(1/x)dx) = exp(ln x) = x",
    explanationLatex: "\\mu = e^{\\int \\frac{1}{x}dx} = e^{\\ln x} = x",
    references: [{ label: "Integrating Factor", url: "https://en.wikipedia.org/wiki/Integrating_factor" }],
  },
  {
    id: "diff-009",
    topic: "differential",
    prompt: "The Wronskian of y₁ = eˣ and y₂ = e²ˣ is:",
    promptLatex: "y_1 = e^x, \\quad y_2 = e^{2x}",
    options: ["e³ˣ", "e²ˣ", "eˣ (e²ˣ - eˣ)", "0"],
    optionsLatex: [
      "e^{3x}",
      "e^{2x}",
      "e^x(e^{2x} - e^x)",
      "0",
    ],
    answerIndex: 0,
    explanation: "W = y₁y₂' - y₂y₁' = eˣ·2e²ˣ - e²ˣ·eˣ = 2e³ˣ - e³ˣ = e³ˣ.",
    explanationLatex: "W = y_1 y_2' - y_2 y_1' = e^x \\cdot 2e^{2x} - e^{2x} \\cdot e^x = e^{3x}",
    references: [{ label: "Wronskian", url: "https://en.wikipedia.org/wiki/Wronskian" }],
  },
  {
    id: "diff-010",
    topic: "differential",
    prompt: "Solve: d²y/dx² - y = 0.",
    promptLatex: "\\frac{d^2 y}{dx^2} - y = 0",
    options: ["y = Aeˣ + Be⁻ˣ", "y = Aeˣ + Beˣ", "y = A cos(x) + B sin(x)", "y = A cosh(x)"],
    optionsLatex: [
      "y = Ae^x + Be^{-x}",
      "y = Ae^x + Be^x",
      "y = A\\cos x + B\\sin x",
      "y = A\\cosh x",
    ],
    answerIndex: 0,
    explanation: "Auxiliary equation: r² - 1 = 0 ⇒ r = ±1. General solution: y = Aeˣ + Be⁻ˣ.",
    explanationLatex: "r^2 - 1 = 0 \\implies r = \\pm 1 \\implies y = Ae^x + Be^{-x}",
    references: [{ label: "Second Order Linear ODE", url: "https://en.wikipedia.org/wiki/Linear_differential_equation" }],
  },
];
