import type { QuizQuestion } from "./types";

export const discreteQuestions: QuizQuestion[] = [
  {
    id: "discrete-001",
    topic: "discrete",
    prompt: "If A = {1,2,3} and B = {2,3,4}, find A ∪ B.",
    promptLatex: "A = \\{1,2,3\\}, \\; B = \\{2,3,4\\}",
    options: ["{1,2,3,4}", "{2,3}", "{1,2,3}", "{4}"],
    optionsLatex: [
      "\\{1,2,3,4\\}",
      "\\{2,3\\}",
      "\\{1,2,3\\}",
      "\\{4\\}",
    ],
    answerIndex: 0,
    explanation: "Union contains all elements from both sets: {1,2,3,4}",
    explanationLatex: "A \\cup B = \\{1,2,3,4\\}",
    references: [{ label: "Set Theory", url: "https://en.wikipedia.org/wiki/Set_(mathematics)" }],
  },
  {
    id: "discrete-002",
    topic: "discrete",
    prompt: "How many ways can 3 books be arranged on a shelf?",
    options: ["3", "6", "9", "27"],
    answerIndex: 1,
    explanation: "3! = 3 × 2 × 1 = 6 permutations",
    explanationLatex: "3! = 3 \\times 2 \\times 1 = 6",
    references: [{ label: "Permutation", url: "https://en.wikipedia.org/wiki/Permutation" }],
  },
  {
    id: "discrete-003",
    topic: "discrete",
    prompt: "In propositional logic, p → q is equivalent to:",
    options: ["¬p ∨ q", "p ∨ ¬q", "¬p ∧ q", "¬(p ∨ q)"],
    optionsLatex: [
      "\\neg p \\lor q",
      "p \\lor \\neg q",
      "\\neg p \\land q",
      "\\neg(p \\lor q)",
    ],
    answerIndex: 0,
    explanation: "The implication p → q is logically equivalent to ¬p ∨ q.",
    explanationLatex: "p \\to q \\equiv \\neg p \\lor q",
    references: [{ label: "Logical Implication", url: "https://en.wikipedia.org/wiki/Material_conditional" }],
  },
  {
    id: "discrete-004",
    topic: "discrete",
    prompt: "What is the cardinality of the power set of {a,b,c}?",
    promptLatex: "P(\\{a,b,c\\})",
    options: ["3", "6", "8", "9"],
    answerIndex: 2,
    explanation: "Power set has 2ⁿ elements. n=3, so |P(S)| = 2³ = 8.",
    explanationLatex: "|P(S)| = 2^3 = 8",
    references: [{ label: "Power Set", url: "https://en.wikipedia.org/wiki/Power_set" }],
  },
  {
    id: "discrete-005",
    topic: "discrete",
    prompt: "A relation R is symmetric if:",
    options: [
      "aRb implies bRa",
      "aRa for all a",
      "aRb and bRc implies aRc",
      "aRb implies aRc",
    ],
    answerIndex: 0,
    explanation: "Symmetric: if (a,b) ∈ R then (b,a) ∈ R for all a,b.",
    explanationLatex: "aRb \\implies bRa",
    references: [{ label: "Relation Properties", url: "https://en.wikipedia.org/wiki/Binary_relation" }],
  },
  {
    id: "discrete-006",
    topic: "discrete",
    prompt: "How many edges does a complete graph K₅ have?",
    promptLatex: "K_5",
    options: ["5", "10", "15", "20"],
    answerIndex: 1,
    explanation: "Complete graph Kₙ has n(n-1)/2 edges. K₅ has 5·4/2 = 10 edges.",
    explanationLatex: "|E(K_5)| = \\frac{5 \\cdot 4}{2} = 10",
    references: [{ label: "Complete Graph", url: "https://en.wikipedia.org/wiki/Complete_graph" }],
  },
  {
    id: "discrete-007",
    topic: "discrete",
    prompt: "The sum of degrees in any graph equals:",
    options: ["Twice the number of edges", "Number of edges", "Number of vertices", "Twice the number of vertices"],
    answerIndex: 0,
    explanation: "Handshaking Lemma: Σ deg(v) = 2|E|",
    explanationLatex: "\\sum_{v \\in V} \\deg(v) = 2|E|",
    references: [{ label: "Handshaking Lemma", url: "https://en.wikipedia.org/wiki/Handshaking_lemma" }],
  },
  {
    id: "discrete-008",
    topic: "discrete",
    prompt: "In how many ways can 5 people be chosen from 10?",
    options: ["120", "252", "5040", "100"],
    answerIndex: 1,
    explanation: "C(10,5) = 10!/(5!·5!) = 252",
    explanationLatex: "\\binom{10}{5} = \\frac{10!}{5!\\,5!} = 252",
    references: [{ label: "Combination", url: "https://en.wikipedia.org/wiki/Combination" }],
  },
  {
    id: "discrete-009",
    topic: "discrete",
    prompt: "A graph that contains a Hamiltonian cycle is called:",
    options: ["Hamiltonian", "Eulerian", "Complete", "Bipartite"],
    answerIndex: 0,
    explanation: "A graph with a Hamiltonian cycle is called a Hamiltonian graph.",
    references: [{ label: "Hamiltonian Path", url: "https://en.wikipedia.org/wiki/Hamiltonian_path" }],
  },
  {
    id: "discrete-010",
    topic: "discrete",
    prompt: "What is the negation of ∀x P(x)?",
    promptLatex: "\\forall x \\, P(x)",
    options: ["∃x ¬P(x)", "¬∃x P(x)", "∀x ¬P(x)", "∃x P(x)"],
    optionsLatex: [
      "\\exists x \\, \\neg P(x)",
      "\\neg \\exists x \\, P(x)",
      "\\forall x \\, \\neg P(x)",
      "\\exists x \\, P(x)",
    ],
    answerIndex: 0,
    explanation: "¬∀x P(x) ≡ ∃x ¬P(x). The negation of 'for all x, P(x)' is 'exists x such that not P(x)'.",
    explanationLatex: "\\neg \\forall x \\, P(x) \\equiv \\exists x \\, \\neg P(x)",
    references: [{ label: "Quantifier Negation", url: "https://en.wikipedia.org/wiki/Universal_quantification" }],
  },
];
