import type { QuizQuestion } from "./types";

export const graphicsQuestions: QuizQuestion[] = [
  {
    id: "graphics-001",
    topic: "graphics",
    prompt: "In first-angle projection, the object is placed in which quadrant?",
    options: ["First", "Second", "Third", "Fourth"],
    answerIndex: 0,
    explanation: "In first-angle projection, the object is placed in the first quadrant between observer and plane.",
    references: [{ label: "Orthographic Projection", url: "https://en.wikipedia.org/wiki/Orthographic_projection" }],
  },
  {
    id: "graphics-002",
    topic: "graphics",
    prompt: "In third-angle projection, the plane is located _____ the object.",
    options: ["Between observer and", "Behind", "Above", "Below"],
    answerIndex: 0,
    explanation: "In third-angle projection, the projection plane is between the observer and the object.",
    references: [{ label: "Third Angle Projection", url: "https://en.wikipedia.org/wiki/Multiview_projection" }],
  },
  {
    id: "graphics-003",
    topic: "graphics",
    prompt: "What type of line is used to represent hidden edges in engineering drawings?",
    options: ["Dashed line", "Solid thick line", "Chain line", "Wavy line"],
    answerIndex: 0,
    explanation: "Hidden edges and surfaces are shown using dashed (hidden) lines.",
    references: [{ label: "Engineering Drawing", url: "https://en.wikipedia.org/wiki/Engineering_drawing" }],
  },
  {
    id: "graphics-004",
    topic: "graphics",
    prompt: "In isometric projection, the angles between axes are:",
    options: ["120°", "90°", "60°", "180°"],
    answerIndex: 0,
    explanation: "In isometric projection, all three axes are 120° apart.",
    explanationLatex: "120^\\circ \\text{ between each pair of axes}",
    references: [{ label: "Isometric Projection", url: "https://en.wikipedia.org/wiki/Isometric_projection" }],
  },
  {
    id: "graphics-005",
    topic: "graphics",
    prompt: "The scale used in isometric drawing is:",
    options: ["Full scale", "Isometric scale", "Reduced scale", "Enlarged scale"],
    answerIndex: 1,
    explanation: "Isometric drawings use an isometric scale where measurements along isometric axes are true lengths.",
    references: [{ label: "Isometric Scale", url: "https://en.wikipedia.org/wiki/Isometric_projection" }],
  },
  {
    id: "graphics-006",
    topic: "graphics",
    prompt: "What is the angle between the horizontal and isometric axes in isometric projection?",
    options: ["30°", "45°", "60°", "90°"],
    answerIndex: 0,
    explanation: "Isometric axes are drawn at 30° to the horizontal.",
    explanationLatex: "30^\\circ \\text{ to the horizontal}",
    references: [{ label: "Isometric Axes", url: "https://en.wikipedia.org/wiki/Axonometric_projection" }],
  },
  {
    id: "graphics-007",
    topic: "graphics",
    prompt: "A section line in engineering drawing is typically shown as a:",
    options: ["Thin chain line with thick ends", "Thick continuous line", "Dashed line", "Wavy line"],
    answerIndex: 0,
    explanation: "Cutting plane lines (section lines) are shown as thin chain lines with thick line ends.",
    references: [{ label: "Section Views", url: "https://en.wikipedia.org/wiki/Section_view" }],
  },
  {
    id: "graphics-008",
    topic: "graphics",
    prompt: "Which type of projection uses parallel projectors perpendicular to the projection plane?",
    options: ["Orthographic", "Perspective", "Oblique", "Isometric"],
    answerIndex: 0,
    explanation: "Orthographic projection uses parallel projectors perpendicular to the projection plane.",
    references: [{ label: "Orthographic Projection", url: "https://en.wikipedia.org/wiki/Orthographic_projection" }],
  },
  {
    id: "graphics-009",
    topic: "graphics",
    prompt: "In a perspective projection, lines converging at a point are called:",
    options: ["Projectors", "Vanishing lines", "Horizon lines", "Converging lines"],
    answerIndex: 1,
    explanation: "Imaginary lines along which parallel lines converge to a vanishing point.",
    references: [{ label: "Perspective Projection", url: "https://en.wikipedia.org/wiki/Perspective_(graphical)" }],
  },
  {
    id: "graphics-010",
    topic: "graphics",
    prompt: "The standard drawing sheet size A4 has dimensions:",
    options: ["297×210 mm", "420×297 mm", "210×148 mm", "594×420 mm"],
    answerIndex: 2,
    explanation: "A4 is 210 mm × 297 mm (width × height in portrait orientation).",
    references: [{ label: "Paper Size", url: "https://en.wikipedia.org/wiki/Paper_size" }],
  },
];
