import type { QuizQuestion } from "./types";

export const mathsQuestions: QuizQuestion[] = [
  {
    id: "maths-001",
    topic: "maths",
    prompt: "Evaluate the limit: lim(x→0) sin(x)/x",
    promptLatex: "\\lim_{x \\to 0} \\frac{\\sin x}{x}",
    options: ["0", "1", "∞", "Does not exist"],
    optionsLatex: ["0", "1", "\\infty", "\\text{DNE}"],
    answerIndex: 1,
    explanation: "This is a standard limit in calculus. Using the squeeze theorem or L'Hôpital's rule, the limit equals 1.",
    explanationLatex: "\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1",
    references: [{ label: "Standard Limits", url: "https://en.wikipedia.org/wiki/Limit_of_a_function" }],
  },
  {
    id: "maths-002",
    topic: "maths",
    prompt: "Find the derivative of f(x) = x² sin(x)",
    promptLatex: "f(x) = x^2 \\sin x",
    options: ["2x sin(x)", "2x sin(x) + x² cos(x)", "x² cos(x)", "2x cos(x)"],
    optionsLatex: [
      "2x \\sin x",
      "2x \\sin x + x^2 \\cos x",
      "x^2 \\cos x",
      "2x \\cos x",
    ],
    answerIndex: 1,
    explanation: "Using the product rule: (x²)'·sin(x) + x²·(sin(x))' = 2x sin(x) + x² cos(x)",
    explanationLatex: "f'(x) = 2x \\sin x + x^2 \\cos x",
    references: [{ label: "Product Rule", url: "https://en.wikipedia.org/wiki/Product_rule" }],
  },
  {
    id: "maths-003",
    topic: "maths",
    prompt: "Evaluate the integral: ∫(3x² + 2x + 1)dx",
    promptLatex: "\\int (3x^2 + 2x + 1) \\, dx",
    options: ["x³ + x² + x + C", "3x³ + 2x² + x + C", "x³ + x² + C", "6x + 2 + C"],
    optionsLatex: [
      "x^3 + x^2 + x + C",
      "3x^3 + 2x^2 + x + C",
      "x^3 + x^2 + C",
      "6x + 2 + C",
    ],
    answerIndex: 0,
    explanation: "Integrate term by term: ∫3x² dx = x³, ∫2x dx = x², ∫1 dx = x",
    explanationLatex: "\\int (3x^2 + 2x + 1) \\, dx = x^3 + x^2 + x + C",
    references: [{ label: "Integration Rules", url: "https://en.wikipedia.org/wiki/Integral" }],
  },
  {
    id: "maths-004",
    topic: "maths",
    prompt: "What is the value of log₂(32)?",
    promptLatex: "\\log_2 32",
    options: ["4", "5", "6", "16"],
    answerIndex: 1,
    explanation: "2⁵ = 32, so log₂(32) = 5",
    explanationLatex: "\\log_2 32 = 5 \\text{ since } 2^5 = 32",
    references: [{ label: "Logarithms", url: "https://en.wikipedia.org/wiki/Logarithm" }],
  },
  {
    id: "maths-005",
    topic: "maths",
    prompt: "Factorize: x² - 5x + 6",
    promptLatex: "x^2 - 5x + 6",
    options: ["(x-2)(x-3)", "(x+2)(x+3)", "(x-1)(x-6)", "(x+1)(x-6)"],
    optionsLatex: [
      "(x-2)(x-3)",
      "(x+2)(x+3)",
      "(x-1)(x-6)",
      "(x+1)(x-6)",
    ],
    answerIndex: 0,
    explanation: "x² - 5x + 6 = (x-2)(x-3) since -2 × -3 = 6 and -2 + -3 = -5",
    explanationLatex: "x^2 - 5x + 6 = (x-2)(x-3)",
    references: [{ label: "Factorization", url: "https://en.wikipedia.org/wiki/Factorization" }],
  },
  {
    id: "maths-006",
    topic: "maths",
    prompt: "Find sin²(θ) + cos²(θ)",
    promptLatex: "\\sin^2 \\theta + \\cos^2 \\theta",
    options: ["0", "1", "sin(2θ)", "cos(2θ)"],
    optionsLatex: ["0", "1", "\\sin 2\\theta", "\\cos 2\\theta"],
    answerIndex: 1,
    explanation: "This is the Pythagorean trigonometric identity. It always equals 1.",
    explanationLatex: "\\sin^2 \\theta + \\cos^2 \\theta = 1",
    references: [{ label: "Trigonometric Identity", url: "https://en.wikipedia.org/wiki/Pythagorean_trigonometric_identity" }],
  },
  {
    id: "maths-007",
    topic: "maths",
    prompt: "What is the Taylor series expansion of e^x about x=0?",
    promptLatex: "e^x \\text{ about } x=0",
    options: [
      "Σ xⁿ/n!",
      "Σ xⁿ",
      "Σ (-1)ⁿ xⁿ/n!",
      "Σ n! xⁿ",
    ],
    optionsLatex: [
      "\\sum_{n=0}^{\\infty} \\frac{x^n}{n!}",
      "\\sum_{n=0}^{\\infty} x^n",
      "\\sum_{n=0}^{\\infty} \\frac{(-1)^n x^n}{n!}",
      "\\sum_{n=0}^{\\infty} n! \\, x^n",
    ],
    answerIndex: 0,
    explanation: "The Maclaurin series for eˣ is Σ xⁿ/n! for n=0 to ∞",
    explanationLatex: "e^x = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!}",
    references: [{ label: "Taylor Series", url: "https://en.wikipedia.org/wiki/Taylor_series" }],
  },
  {
    id: "maths-008",
    topic: "maths",
    prompt: "Solve for x: 2ˣ = 8",
    promptLatex: "2^x = 8",
    options: ["2", "3", "4", "16"],
    answerIndex: 1,
    explanation: "2³ = 8, therefore x = 3",
    explanationLatex: "2^x = 8 \\implies x = 3",
    references: [{ label: "Exponents", url: "https://en.wikipedia.org/wiki/Exponentiation" }],
  },
  {
    id: "maths-009",
    topic: "maths",
    prompt: "What is the area under the curve y = 1/x from x=1 to x=e?",
    promptLatex: "\\int_1^e \\frac{1}{x} \\, dx",
    options: ["0", "1", "e-1", "ln(e)"],
    answerIndex: 1,
    explanation: "∫₁ᵉ (1/x) dx = [ln|x|]₁ᵉ = ln(e) - ln(1) = 1 - 0 = 1",
    explanationLatex: "\\int_1^e \\frac{1}{x} \\, dx = [\\ln x]_1^e = \\ln e - \\ln 1 = 1",
    references: [{ label: "Natural Logarithm", url: "https://en.wikipedia.org/wiki/Natural_logarithm" }],
  },
  {
    id: "maths-010",
    topic: "maths",
    prompt: "Find cos(π/3)",
    promptLatex: "\\cos(\\pi/3)",
    options: ["0", "1/2", "√3/2", "1"],
    optionsLatex: ["0", "\\frac{1}{2}", "\\frac{\\sqrt{3}}{2}", "1"],
    answerIndex: 1,
    explanation: "cos(π/3) = cos(60°) = 1/2",
    explanationLatex: "\\cos(\\pi/3) = \\frac{1}{2}",
    references: [{ label: "Trigonometry", url: "https://en.wikipedia.org/wiki/Trigonometric_functions" }],
  },
];
