import type { QuizQuestion } from "./types";

const discreteMerged: QuizQuestion[] = [
  {
    id: "discrete-001",
    topic: "maths",
    prompt: "If A = {1,2,3} and B = {2,3,4}, find A ∪ B.",
    promptLatex: "A = \\{1,2,3\\}, \\; B = \\{2,3,4\\}",
    options: ["{1,2,3,4}", "{2,3}", "{1,2,3}", "{4}"],
    optionsLatex: [
      "\\{1,2,3,4\\}",
      "\\{2,3\\}",
      "\\{1,2,3\\}",
      "\\{4\\}",
    ],
    answerIndex: 0,
    explanation: "Union contains all elements from both sets: {1,2,3,4}",
    explanationLatex: "A \\cup B = \\{1,2,3,4\\}",
    references: [{ label: "Set Theory", url: "https://en.wikipedia.org/wiki/Set_(mathematics)" }],
  },
  {
    id: "discrete-002",
    topic: "maths",
    prompt: "How many ways can 3 books be arranged on a shelf?",
    options: ["3", "6", "9", "27"],
    answerIndex: 1,
    explanation: "3! = 3 × 2 × 1 = 6 permutations",
    explanationLatex: "3! = 3 \\times 2 \\times 1 = 6",
    references: [{ label: "Permutation", url: "https://en.wikipedia.org/wiki/Permutation" }],
  },
  {
    id: "discrete-003",
    topic: "maths",
    prompt: "In propositional logic, p → q is equivalent to:",
    options: ["¬p ∨ q", "p ∨ ¬q", "¬p ∧ q", "¬(p ∨ q)"],
    optionsLatex: [
      "\\neg p \\lor q",
      "p \\lor \\neg q",
      "\\neg p \\land q",
      "\\neg(p \\lor q)",
    ],
    answerIndex: 0,
    explanation: "The implication p → q is logically equivalent to ¬p ∨ q.",
    explanationLatex: "p \\to q \\equiv \\neg p \\lor q",
    references: [{ label: "Logical Implication", url: "https://en.wikipedia.org/wiki/Material_conditional" }],
  },
  {
    id: "discrete-004",
    topic: "maths",
    prompt: "What is the cardinality of the power set of {a,b,c}?",
    promptLatex: "P(\\{a,b,c\\})",
    options: ["3", "6", "8", "9"],
    answerIndex: 2,
    explanation: "Power set has 2ⁿ elements. n=3, so |P(S)| = 2³ = 8.",
    explanationLatex: "|P(S)| = 2^3 = 8",
    references: [{ label: "Power Set", url: "https://en.wikipedia.org/wiki/Power_set" }],
  },
  {
    id: "discrete-005",
    topic: "maths",
    prompt: "A relation R is symmetric if:",
    options: [
      "aRb implies bRa",
      "aRa for all a",
      "aRb and bRc implies aRc",
      "aRb implies aRc",
    ],
    answerIndex: 0,
    explanation: "Symmetric: if (a,b) ∈ R then (b,a) ∈ R for all a,b.",
    explanationLatex: "aRb \\implies bRa",
    references: [{ label: "Relation Properties", url: "https://en.wikipedia.org/wiki/Binary_relation" }],
  },
  {
    id: "discrete-006",
    topic: "maths",
    prompt: "How many edges does a complete graph K₅ have?",
    promptLatex: "K_5",
    options: ["5", "10", "15", "20"],
    answerIndex: 1,
    explanation: "Complete graph Kₙ has n(n-1)/2 edges. K₅ has 5·4/2 = 10 edges.",
    explanationLatex: "|E(K_5)| = \\frac{5 \\cdot 4}{2} = 10",
    references: [{ label: "Complete Graph", url: "https://en.wikipedia.org/wiki/Complete_graph" }],
  },
  {
    id: "discrete-007",
    topic: "maths",
    prompt: "The sum of degrees in any graph equals:",
    options: ["Twice the number of edges", "Number of edges", "Number of vertices", "Twice the number of vertices"],
    answerIndex: 0,
    explanation: "Handshaking Lemma: Σ deg(v) = 2|E|",
    explanationLatex: "\\sum_{v \\in V} \\deg(v) = 2|E|",
    references: [{ label: "Handshaking Lemma", url: "https://en.wikipedia.org/wiki/Handshaking_lemma" }],
  },
  {
    id: "discrete-008",
    topic: "maths",
    prompt: "In how many ways can 5 people be chosen from 10?",
    options: ["120", "252", "5040", "100"],
    answerIndex: 1,
    explanation: "C(10,5) = 10!/(5!·5!) = 252",
    explanationLatex: "\\binom{10}{5} = \\frac{10!}{5!\\,5!} = 252",
    references: [{ label: "Combination", url: "https://en.wikipedia.org/wiki/Combination" }],
  },
  {
    id: "discrete-009",
    topic: "maths",
    prompt: "A graph that contains a Hamiltonian cycle is called:",
    options: ["Hamiltonian", "Eulerian", "Complete", "Bipartite"],
    answerIndex: 0,
    explanation: "A graph with a Hamiltonian cycle is called a Hamiltonian graph.",
    references: [{ label: "Hamiltonian Path", url: "https://en.wikipedia.org/wiki/Hamiltonian_path" }],
  },
  {
    id: "discrete-010",
    topic: "maths",
    prompt: "What is the negation of ∀x P(x)?",
    promptLatex: "\\forall x \\, P(x)",
    options: ["∃x ¬P(x)", "¬∃x P(x)", "∀x ¬P(x)", "∃x P(x)"],
    optionsLatex: [
      "\\exists x \\, \\neg P(x)",
      "\\neg \\exists x \\, P(x)",
      "\\forall x \\, \\neg P(x)",
      "\\exists x \\, P(x)",
    ],
    answerIndex: 0,
    explanation: "¬∀x P(x) ≡ ∃x ¬P(x). The negation of 'for all x, P(x)' is 'exists x such that not P(x)'.",
    explanationLatex: "\\neg \\forall x \\, P(x) \\equiv \\exists x \\, \\neg P(x)",
    references: [{ label: "Quantifier Negation", url: "https://en.wikipedia.org/wiki/Universal_quantification" }],
  },
];

export const mathsQuestions: QuizQuestion[] = [
  {
    id: "maths-001",
    topic: "maths",
    prompt: "Evaluate the limit: lim(x→0) sin(x)/x",
    promptLatex: "\\lim_{x \\to 0} \\frac{\\sin x}{x}",
    options: ["0", "1", "∞", "Does not exist"],
    optionsLatex: ["0", "1", "\\infty", "\\text{DNE}"],
    answerIndex: 1,
    explanation: "This is a standard limit in calculus. Using the squeeze theorem or L'Hôpital's rule, the limit equals 1.",
    explanationLatex: "\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1",
    references: [{ label: "Standard Limits", url: "https://en.wikipedia.org/wiki/Limit_of_a_function" }],
  },
  {
    id: "maths-002",
    topic: "maths",
    prompt: "Find the derivative of f(x) = x² sin(x)",
    promptLatex: "f(x) = x^2 \\sin x",
    options: ["2x sin(x)", "2x sin(x) + x² cos(x)", "x² cos(x)", "2x cos(x)"],
    optionsLatex: [
      "2x \\sin x",
      "2x \\sin x + x^2 \\cos x",
      "x^2 \\cos x",
      "2x \\cos x",
    ],
    answerIndex: 1,
    explanation: "Using the product rule: (x²)'·sin(x) + x²·(sin(x))' = 2x sin(x) + x² cos(x)",
    explanationLatex: "f'(x) = 2x \\sin x + x^2 \\cos x",
    references: [{ label: "Product Rule", url: "https://en.wikipedia.org/wiki/Product_rule" }],
  },
  {
    id: "maths-003",
    topic: "maths",
    prompt: "Evaluate the integral: ∫(3x² + 2x + 1)dx",
    promptLatex: "\\int (3x^2 + 2x + 1) \\, dx",
    options: ["x³ + x² + x + C", "3x³ + 2x² + x + C", "x³ + x² + C", "6x + 2 + C"],
    optionsLatex: [
      "x^3 + x^2 + x + C",
      "3x^3 + 2x^2 + x + C",
      "x^3 + x^2 + C",
      "6x + 2 + C",
    ],
    answerIndex: 0,
    explanation: "Integrate term by term: ∫3x² dx = x³, ∫2x dx = x², ∫1 dx = x",
    explanationLatex: "\\int (3x^2 + 2x + 1) \\, dx = x^3 + x^2 + x + C",
    references: [{ label: "Integration Rules", url: "https://en.wikipedia.org/wiki/Integral" }],
  },
  {
    id: "maths-004",
    topic: "maths",
    prompt: "What is the value of log₂(32)?",
    promptLatex: "\\log_2 32",
    options: ["4", "5", "6", "16"],
    answerIndex: 1,
    explanation: "2⁵ = 32, so log₂(32) = 5",
    explanationLatex: "\\log_2 32 = 5 \\text{ since } 2^5 = 32",
    references: [{ label: "Logarithms", url: "https://en.wikipedia.org/wiki/Logarithm" }],
  },
  {
    id: "maths-005",
    topic: "maths",
    prompt: "Factorize: x² - 5x + 6",
    promptLatex: "x^2 - 5x + 6",
    options: ["(x-2)(x-3)", "(x+2)(x+3)", "(x-1)(x-6)", "(x+1)(x-6)"],
    optionsLatex: [
      "(x-2)(x-3)",
      "(x+2)(x+3)",
      "(x-1)(x-6)",
      "(x+1)(x-6)",
    ],
    answerIndex: 0,
    explanation: "x² - 5x + 6 = (x-2)(x-3) since -2 × -3 = 6 and -2 + -3 = -5",
    explanationLatex: "x^2 - 5x + 6 = (x-2)(x-3)",
    references: [{ label: "Factorization", url: "https://en.wikipedia.org/wiki/Factorization" }],
  },
  {
    id: "maths-006",
    topic: "maths",
    prompt: "Find sin²(θ) + cos²(θ)",
    promptLatex: "\\sin^2 \\theta + \\cos^2 \\theta",
    options: ["0", "1", "sin(2θ)", "cos(2θ)"],
    optionsLatex: ["0", "1", "\\sin 2\\theta", "\\cos 2\\theta"],
    answerIndex: 1,
    explanation: "This is the Pythagorean trigonometric identity. It always equals 1.",
    explanationLatex: "\\sin^2 \\theta + \\cos^2 \\theta = 1",
    references: [{ label: "Trigonometric Identity", url: "https://en.wikipedia.org/wiki/Pythagorean_trigonometric_identity" }],
  },
  {
    id: "maths-007",
    topic: "maths",
    prompt: "What is the Taylor series expansion of e^x about x=0?",
    promptLatex: "e^x \\text{ about } x=0",
    options: [
      "Σ xⁿ/n!",
      "Σ xⁿ",
      "Σ (-1)ⁿ xⁿ/n!",
      "Σ n! xⁿ",
    ],
    optionsLatex: [
      "\\sum_{n=0}^{\\infty} \\frac{x^n}{n!}",
      "\\sum_{n=0}^{\\infty} x^n",
      "\\sum_{n=0}^{\\infty} \\frac{(-1)^n x^n}{n!}",
      "\\sum_{n=0}^{\\infty} n! \\, x^n",
    ],
    answerIndex: 0,
    explanation: "The Maclaurin series for eˣ is Σ xⁿ/n! for n=0 to ∞",
    explanationLatex: "e^x = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!}",
    references: [{ label: "Taylor Series", url: "https://en.wikipedia.org/wiki/Taylor_series" }],
  },
  {
    id: "maths-008",
    topic: "maths",
    prompt: "Solve for x: 2ˣ = 8",
    promptLatex: "2^x = 8",
    options: ["2", "3", "4", "16"],
    answerIndex: 1,
    explanation: "2³ = 8, therefore x = 3",
    explanationLatex: "2^x = 8 \\implies x = 3",
    references: [{ label: "Exponents", url: "https://en.wikipedia.org/wiki/Exponentiation" }],
  },
  {
    id: "maths-009",
    topic: "maths",
    prompt: "What is the area under the curve y = 1/x from x=1 to x=e?",
    promptLatex: "\\int_1^e \\frac{1}{x} \\, dx",
    options: ["0", "1", "e-1", "ln(e)"],
    answerIndex: 1,
    explanation: "∫₁ᵉ (1/x) dx = [ln|x|]₁ᵉ = ln(e) - ln(1) = 1 - 0 = 1",
    explanationLatex: "\\int_1^e \\frac{1}{x} \\, dx = [\\ln x]_1^e = \\ln e - \\ln 1 = 1",
    references: [{ label: "Natural Logarithm", url: "https://en.wikipedia.org/wiki/Natural_logarithm" }],
  },
  {
    id: "maths-010",
    topic: "maths",
    prompt: "Find cos(π/3)",
    promptLatex: "\\cos(\\pi/3)",
    options: ["0", "1/2", "√3/2", "1"],
    optionsLatex: ["0", "\\frac{1}{2}", "\\frac{\\sqrt{3}}{2}", "1"],
    answerIndex: 1,
    explanation: "cos(π/3) = cos(60°) = 1/2",
    explanationLatex: "\\cos(\\pi/3) = \\frac{1}{2}",
    references: [{ label: "Trigonometry", url: "https://en.wikipedia.org/wiki/Trigonometric_functions" }],
  },
  ...discreteMerged,
];
