import type { QuizQuestion } from "./types";

export const matrixQuestions: QuizQuestion[] = [
  {
    id: "matrix-001",
    topic: "matrices",
    prompt: "Find the determinant of [[1,2],[3,4]].",
    promptLatex: "\\begin{vmatrix} 1 & 2 \\\\ 3 & 4 \\end{vmatrix}",
    options: ["-2", "2", "4", "-4"],
    answerIndex: 0,
    explanation: "det = (1×4) - (2×3) = 4 - 6 = -2",
    explanationLatex: "\\det = 1 \\cdot 4 - 2 \\cdot 3 = 4 - 6 = -2",
    references: [{ label: "Determinant", url: "https://en.wikipedia.org/wiki/Determinant" }],
  },
  {
    id: "matrix-002",
    topic: "matrices",
    prompt: "If A is a 3×3 matrix with det(A) = 5, what is det(2A)?",
    options: ["10", "20", "40", "8"],
    answerIndex: 2,
    explanation: "det(kA) = kⁿ det(A) where n is the order. det(2A) = 2³ × 5 = 8 × 5 = 40",
    explanationLatex: "\\det(2A) = 2^3 \\cdot \\det(A) = 8 \\cdot 5 = 40",
    references: [{ label: "Determinant Properties", url: "https://en.wikipedia.org/wiki/Determinant#Properties" }],
  },
  {
    id: "matrix-003",
    topic: "matrices",
    prompt: "What is the product of matrices [[1,0],[0,1]] and [[a,b],[c,d]]?",
    promptLatex: "\\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix} \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}",
    options: [
      "[[a,b],[c,d]]",
      "[[1,0],[0,1]]",
      "[[0,0],[0,0]]",
      "[[a,c],[b,d]]",
    ],
    answerIndex: 0,
    explanation: "Identity matrix times any matrix gives the same matrix.",
    explanationLatex: "I \\cdot M = M",
    references: [{ label: "Identity Matrix", url: "https://en.wikipedia.org/wiki/Identity_matrix" }],
  },
  {
    id: "matrix-004",
    topic: "matrices",
    prompt: "Find the eigenvalues of [[2,0],[0,3]].",
    promptLatex: "\\begin{pmatrix} 2 & 0 \\\\ 0 & 3 \\end{pmatrix}",
    options: ["1, 2", "2, 3", "0, 1", "3, 4"],
    answerIndex: 1,
    explanation: "For a diagonal matrix, eigenvalues are the diagonal entries: λ = 2, 3",
    explanationLatex: "\\lambda_1 = 2, \\quad \\lambda_2 = 3",
    references: [{ label: "Eigenvalues", url: "https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors" }],
  },
  {
    id: "matrix-005",
    topic: "matrices",
    prompt: "What is the rank of [[1,0,0],[0,1,0],[0,0,0]]?",
    promptLatex: "\\begin{pmatrix} 1 & 0 & 0 \\\\ 0 & 1 & 0 \\\\ 0 & 0 & 0 \\end{pmatrix}",
    options: ["1", "2", "3", "0"],
    answerIndex: 1,
    explanation: "There are 2 linearly independent rows (or columns), so rank = 2.",
    references: [{ label: "Rank (Linear Algebra)", url: "https://en.wikipedia.org/wiki/Rank_(linear_algebra)" }],
  },
  {
    id: "matrix-006",
    topic: "matrices",
    prompt: "If A and B are invertible n×n matrices, what is (AB)⁻¹?",
    options: ["A⁻¹B⁻¹", "B⁻¹A⁻¹", "AᵀBᵀ", "(BA)⁻¹"],
    optionsLatex: [
      "A^{-1}B^{-1}",
      "B^{-1}A^{-1}",
      "A^T B^T",
      "(BA)^{-1}",
    ],
    answerIndex: 1,
    explanation: "(AB)⁻¹ = B⁻¹A⁻¹ (reverse order)",
    explanationLatex: "(AB)^{-1} = B^{-1}A^{-1}",
    references: [{ label: "Inverse Matrix", url: "https://en.wikipedia.org/wiki/Invertible_matrix" }],
  },
  {
    id: "matrix-007",
    topic: "matrices",
    prompt: "Find the trace of [[1,2,3],[4,5,6],[7,8,9]].",
    promptLatex: "\\begin{pmatrix} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\\\ 7 & 8 & 9 \\end{pmatrix}",
    options: ["15", "12", "45", "24"],
    answerIndex: 0,
    explanation: "Trace = sum of diagonal elements = 1 + 5 + 9 = 15",
    explanationLatex: "\\text{tr} = 1 + 5 + 9 = 15",
    references: [{ label: "Trace (Linear Algebra)", url: "https://en.wikipedia.org/wiki/Trace_(linear_algebra)" }],
  },
  {
    id: "matrix-008",
    topic: "matrices",
    prompt: "What does det(A) = 0 indicate about matrix A?",
    promptLatex: "\\det(A) = 0",
    options: ["A is invertible", "A is singular", "A is symmetric", "A is diagonal"],
    answerIndex: 1,
    explanation: "Zero determinant means the matrix is singular (non-invertible).",
    references: [{ label: "Singular Matrix", url: "https://en.wikipedia.org/wiki/Invertible_matrix" }],
  },
  {
    id: "matrix-009",
    topic: "matrices",
    prompt: "Find the determinant of the 3×3 identity matrix.",
    promptLatex: "\\det(I_3)",
    options: ["0", "1", "2", "3"],
    answerIndex: 1,
    explanation: "The determinant of any identity matrix is 1.",
    explanationLatex: "\\det(I_n) = 1",
    references: [{ label: "Identity Matrix", url: "https://en.wikipedia.org/wiki/Identity_matrix" }],
  },
  {
    id: "matrix-010",
    topic: "matrices",
    prompt: "If Aᵀ = A, the matrix is called:",
    promptLatex: "A^T = A",
    options: ["Skew-symmetric", "Symmetric", "Orthogonal", "Hermitian"],
    answerIndex: 1,
    explanation: "A matrix equal to its transpose is symmetric.",
    references: [{ label: "Symmetric Matrix", url: "https://en.wikipedia.org/wiki/Symmetric_matrix" }],
  },
];
