import type { QuizQuestion } from "./types";

export const vectorQuestions: QuizQuestion[] = [
  {
    id: "vector-001",
    topic: "vectors",
    prompt: "If vector r = xi + yj + zk, find the divergence of r.",
    promptLatex: "\\vec{r} = xi + yj + zk",
    options: ["0", "1", "2", "3"],
    answerIndex: 3,
    explanation: "Divergence is the sum of partial derivatives: ∂x/∂x + ∂y/∂y + ∂z/∂z = 3",
    explanationLatex: "\\nabla \\cdot \\vec{r} = \\frac{\\partial x}{\\partial x} + \\frac{\\partial y}{\\partial y} + \\frac{\\partial z}{\\partial z} = 1+1+1 = 3",
    references: [{ label: "Divergence", url: "https://en.wikipedia.org/wiki/Divergence" }],
  },
  {
    id: "vector-002",
    topic: "vectors",
    prompt: "Find the magnitude of vector A = 3i + 4j.",
    promptLatex: "\\vec{A} = 3i + 4j",
    options: ["4", "5", "6", "7"],
    answerIndex: 1,
    explanation: "Magnitude = √(3² + 4²) = √25 = 5",
    explanationLatex: "|\\vec{A}| = \\sqrt{3^2 + 4^2} = \\sqrt{25} = 5",
    references: [{ label: "Vector Magnitude", url: "https://en.wikipedia.org/wiki/Euclidean_vector" }],
  },
  {
    id: "vector-003",
    topic: "vectors",
    prompt: "Find the dot product: (i + 2j) · (2i + 3j).",
    promptLatex: "\\vec{A} = i + 2j, \\quad \\vec{B} = 2i + 3j",
    options: ["6", "7", "8", "9"],
    answerIndex: 2,
    explanation: "Dot product = (1)(2) + (2)(3) = 8",
    explanationLatex: "\\vec{A} \\cdot \\vec{B} = (1)(2) + (2)(3) = 8",
    references: [{ label: "Dot Product", url: "https://en.wikipedia.org/wiki/Dot_product" }],
  },
  {
    id: "vector-004",
    topic: "vectors",
    prompt: "Find the curl of F = yi + zj + xk.",
    promptLatex: "\\vec{F} = yi + zj + xk",
    options: ["i + j + k", "0", "2i + 2j + 2k", "i - j + k"],
    answerIndex: 0,
    explanation: "curl F = ∇ × F = |i j k; ∂/∂x ∂/∂y ∂/∂z; y z x| = i(1) + j(1) + k(1) = i + j + k",
    explanationLatex: "\\nabla \\times \\vec{F} = \\begin{vmatrix} i & j & k \\\\ \\partial_x & \\partial_y & \\partial_z \\\\ y & z & x \\end{vmatrix} = i + j + k",
    references: [{ label: "Curl", url: "https://en.wikipedia.org/wiki/Curl_(mathematics)" }],
  },
  {
    id: "vector-005",
    topic: "vectors",
    prompt: "If vectors A and B are perpendicular, what is their dot product?",
    promptLatex: "\\vec{A} \\perp \\vec{B}",
    options: ["0", "1", "|A||B|", "90"],
    answerIndex: 0,
    explanation: "Perpendicular vectors have cos(90°) = 0, so dot product = 0",
    explanationLatex: "\\vec{A} \\cdot \\vec{B} = |A||B|\\cos 90^\\circ = 0",
    references: [{ label: "Orthogonal Vectors", url: "https://en.wikipedia.org/wiki/Orthogonality" }],
  },
  {
    id: "vector-006",
    topic: "vectors",
    prompt: "Find the gradient of f(x,y,z) = x² + y² + z².",
    promptLatex: "f(x,y,z) = x^2 + y^2 + z^2",
    options: ["2xi + 2yj + 2zk", "xi + yj + zk", "2x + 2y + 2z", "0"],
    optionsLatex: [
      "2xi + 2yj + 2zk",
      "xi + yj + zk",
      "2x + 2y + 2z",
      "0",
    ],
    answerIndex: 0,
    explanation: "Gradient = (∂f/∂x)i + (∂f/∂y)j + (∂f/∂z)k = 2xi + 2yj + 2zk",
    explanationLatex: "\\nabla f = \\frac{\\partial f}{\\partial x}i + \\frac{\\partial f}{\\partial y}j + \\frac{\\partial f}{\\partial z}k = 2xi + 2yj + 2zk",
    references: [{ label: "Gradient", url: "https://en.wikipedia.org/wiki/Gradient" }],
  },
  {
    id: "vector-007",
    topic: "vectors",
    prompt: "What is the cross product of i and j?",
    promptLatex: "i \\times j",
    options: ["i", "j", "k", "0"],
    answerIndex: 2,
    explanation: "Using right-hand rule, i × j = k",
    explanationLatex: "i \\times j = k",
    references: [{ label: "Cross Product", url: "https://en.wikipedia.org/wiki/Cross_product" }],
  },
  {
    id: "vector-008",
    topic: "vectors",
    prompt: "If ∇·F = 0, what is the vector field called?",
    promptLatex: "\\nabla \\cdot \\vec{F} = 0",
    options: ["Solenoidal", "Irrotational", "Conservative", "Harmonic"],
    answerIndex: 0,
    explanation: "A vector field with zero divergence is called solenoidal.",
    references: [{ label: "Solenoidal Field", url: "https://en.wikipedia.org/wiki/Solenoidal_vector_field" }],
  },
  {
    id: "vector-009",
    topic: "vectors",
    prompt: "If ∇ × F = 0, what is the vector field called?",
    promptLatex: "\\nabla \\times \\vec{F} = 0",
    options: ["Solenoidal", "Irrotational", "Divergent", "Rotational"],
    answerIndex: 1,
    explanation: "A vector field with zero curl is called irrotational or conservative.",
    references: [{ label: "Conservative Field", url: "https://en.wikipedia.org/wiki/Conservative_vector_field" }],
  },
  {
    id: "vector-010",
    topic: "vectors",
    prompt: "Compute: ∇²(1/r) where r = |r| and r ≠ 0.",
    promptLatex: "\\nabla^2 \\left(\\frac{1}{r}\\right)",

    options: ["0", "1/r²", "-1/r²", "∞"],
    optionsLatex: ["0", "\\frac{1}{r^2}", "-\\frac{1}{r^2}", "\\infty"],
    answerIndex: 0,
    explanation: "The Laplacian of 1/r is zero everywhere except at r = 0 (it equals -4πδ(r) in distribution sense).",
    explanationLatex: "\\nabla^2 \\left(\\frac{1}{r}\\right) = 0, \\quad r \\neq 0",
    references: [{ label: "Laplacian", url: "https://en.wikipedia.org/wiki/Laplace_operator" }],
  },
];
